### ISSUE TITLE
Can't get sbt to run stomp-benchmark on Ubuntu/Debian

### ISSUE THREAD

**Issue by Zteve** [chirino/stomp-benchmark#7]
### Errors when attempting to run stomp-benchmark with sbt

```
[error] /home/spowell/dev/stomp-benchmark/src/main/scala/com/github/stomp/benchmark/Benchmark.scala:28: value apache is not a member of package org
[error] import org.apache.felix.gogo.commands.basic.DefaultActionPreparator
[error]            ^
```

etc.
### Details to reproduce
- Clone stomp-benchmark using `git clone https://github.com/chirino/stomp-benchmark.git`;
- download indicated `sbt-launch jar` (from: `http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt-launch/0.10.1/sbt-launch.jar`).  _Note: sbt now wholly on github and benchmark link to sbt takes us to the old place._
- setup sbt executable:
  
  java -Xmx512M -jar `dirname $0`/sbt-launch.jar "$*"
  
  as per (stomp-benchmark) instructions;
- execute `sbt update` in project directory.

__First Problem__:  `build.properties` has wrong version of sbt in it -- I cannot get the older one, so I update this from 0.7.4 to 0.10.1
(this gets me further).

__Also__ scala version I have (on Ubuntu or Debian) is 2.7.7 but `build.properties` says 2.8.1 (I do not change this, but even if I do, the same errors result).

When I issue `sbt update`, it runs cleanly.  I then go to `stomp-benchmark` and issue `sbt run -help` or just `sbt run` and I get the following errors:

```
spowell@ubuntu:~/dev/stomp-benchmark$ sbt run -help
Getting org.scala-tools.sbt sbt_2.8.1 0.10.1 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    36 artifacts copied, 0 already retrieved (6414kB/173ms)
[info] Set current project to default-534971 (in build file:/home/spowell/dev/stomp-benchmark/)
[info] Updating {file:/home/spowell/dev/stomp-benchmark/}default-534971...
[info] Done updating.
[info] Compiling 6 Scala sources to /home/spowell/dev/stomp-benchmark/target/scala-2.8.1.final/classes...
[error] /home/spowell/dev/stomp-benchmark/src/main/scala/com/github/stomp/benchmark/Benchmark.scala:28: value apache is not a member of package org
[error] import org.apache.felix.gogo.commands.basic.DefaultActionPreparator
[error]            ^
[error] /home/spowell/dev/stomp-benchmark/src/main/scala/com/github/stomp/benchmark/Benchmark.scala:29: value apache is not a member of package org
[error] import org.apache.felix.service.command.CommandSession
[error]            ^
[error] /home/spowell/dev/stomp-benchmark/src/main/scala/com/github/stomp/benchmark/Benchmark.scala:30: value apache is not a member of package org
[error] import org.apache.felix.gogo.commands.{CommandException, Action, Option => option, Argument => argument, Command => command}
[error]            ^
[error] /home/spowell/dev/stomp-benchmark/src/main/scala/com/github/stomp/benchmark/NonBlockingScenario.scala:22: value fusesource is not a member of package org
[error] import org.fusesource.hawtdispatch._
[error]            ^
[error] four errors found
[error] {file:/home/spowell/dev/stomp-benchmark/}default-534971/compile: Compilation failed
[error] Total time: 14 s, completed Aug 15, 2011 8:03:20 AM
```

Whatever I do I cannot seem to get rid of this error.
### Environments tried

Ubuntu 10.04 (32-bit/64-bit), and Debian 5 64-bit.  Same results.
### Caveats

I am not an SBT user, so I don't know if this is an SBT problem or a stomp-benchmark problem.

**Comment by chirino** [comment]
Yeah this project is setup to use SBT 0.7.4
To get you into a clean state try running the following commands in the `stomp-benchmark` dir:

```
sbt clean
sbt clean-cache
sbt clean-lib
sbt clean-plugins
sbt update
```

**Comment by Zteve** [comment]
Thanks, but the command `sbt clean-cache` didn't appear to work for me at all!

What I did to get further was:
- ignore the redirect on the `sbt` site your pages link to;
- and take [`sbt-launch-0.7.7.jar`](http://simple-build-tool.googlecode.com/files/sbt-launch-0.7.7.jar) from [there](http://code.google.com/p/simple-build-tool/wiki/Setup) instead;
- take a fresh copy of `stomp-benchmark` from git, for good measure;
- execute the sbt update in the `stomp-benchmark` directory (and _not_ the `project` directory, which is what I read from your instructions, and what only appeared to do anything for me before).

I think you should update your information on the `stomp-benchmark` site to clearly identify what version of `sbt` one should use (and where to get it from), and be much more precise about which directory to run the `sbt update` command in.

Thank you for your help.

**Comment by chirino** [comment]
Thanks for the feedback.. I updated the readme to make it more clear.
